service: caseydyke-com
image: tygrdotdev/caseydyke-com

servers:
  - 188.245.88.23

env:
  secret:
    - NEXT_PUBLIC_CMS_URL
    - KAMAL_REGISTRY_PASSWORD

proxy: 
  ssl: true
  host: caseydyke.com
  app_port: 3000
  healthcheck:
    path: /
    interval: 5

registry:
  server: ghcr.io
  username: tygrdotdev
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .

asset_path: /app/.next